"""
Streamlit frontend for the RAG system.
Calls the backend API via HTTP; no direct RAG or model imports.
"""
import os
import requests
import streamlit as st

# API base URL: use API_URL in Docker (e.g. http://api:8001), else local
API_BASE = os.getenv("API_URL", "http://localhost:8001")
QUERY_URL = f"{API_BASE.rstrip('/')}/query"


def main() -> None:
    st.set_page_config(page_title="Local RAG", layout="wide")
    st.title("Local RAG")
    st.markdown("Ask a question over your indexed PDFs. Answers are generated by the backend.")

    question = st.text_input("Question", placeholder="e.g. What are structs in Go?")

    if st.button("Ask") and question.strip():
        with st.spinner("Asking..."):
            try:
                response = requests.post(
                    QUERY_URL,
                    json={"question": question.strip()},
                    timeout=120,
                )
                response.raise_for_status()
                data = response.json()
            except requests.exceptions.RequestException as e:
                st.error(f"Request failed: {e}")
                if hasattr(e, "response") and e.response is not None:
                    st.code(e.response.text[:500] if e.response.text else "No body")
                return

        st.subheader("Answer")
        st.write(data.get("answer", ""))

        sources = data.get("sources") or []
        if sources:
            st.subheader("Sources")
            for i, src in enumerate(sources, 1):
                source_path = src.get("source") or "—"
                chunk_idx = src.get("chunk_index", "—")
                st.caption(f"{i}. {source_path} (chunk {chunk_idx})")
                if src.get("preview"):
                    st.text(src["preview"][:300] + ("..." if len(src.get("preview", "")) > 300 else ""))

        latency = data.get("latency")
        if latency is not None:
            st.caption(f"Latency: {latency:.2f}s")

    st.divider()
    st.caption(f"Backend: {QUERY_URL}")


if __name__ == "__main__":
    main()
